[pytest]
pythonpath = .
testpaths = tests
addopts = -ra -q
markers =
    product: marks tests as product tests (deselect with '-m "not product"')
    email: marks tests as email tests (requires MailHog to run)
